In [1]:
# 配列の形状を変える
import numpy as np

elm_12 = np.arange(12)
elm_12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
elm_12.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.reshape(elm_12, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
elm_12.reshape(3, 4).reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
elm_12.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [7]:
elm_12.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
elm_12.reshape(-1, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [9]:
elm_12.reshape(2, -1, -1)

ValueError: can only specify one unknown dimension

In [10]:
elm_12.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [11]:
elm_12.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
elm_12 == elm_12.reshape(1, -1)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

In [14]:
elm_12.reshape(1, 1, 12)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]])

In [15]:
elm_12.reshape(1, 12, 1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

In [16]:
elm_12.reshape(12, 1, 1)

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [17]:
elm_12[np.newaxis]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [24]:
elm_12[np.newaxis] == elm_12.reshape(1, -1)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

In [25]:
elm_12[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [26]:
np.newaxis is None

True

In [27]:
elm_12[None]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [34]:
elm_12[1, -1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [35]:
# ブロードキャスト
a = np.array([0, 1, 2])
b = np.array([4, 3, 2])
a + b

array([4, 4, 4])

In [36]:
c = np.array([7, 8])
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [37]:
a + 2

array([2, 3, 4])

In [38]:
elm_12.reshape(3, 4) + np.array([1, 2, 3, 4])

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [39]:
elm_12.reshape(3, 4) + np.array([1, 2, 3])

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [40]:
elm_12.reshape(3, 4) + np.array([1, 2, 3]).reshape(-1, 1)

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [42]:
a[np.newaxis, :]

array([[0, 1, 2]])

In [43]:
b[:, np.newaxis]

array([[4],
       [3],
       [2]])

In [44]:
a[np.newaxis, :] + b[:, np.newaxis]

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])