In [2]:
# 数値型の指定
import numpy as np

np.array([1, 2, 3], dtype=np.byte)

array([1, 2, 3], dtype=int8)

In [7]:
print(np.array([1, 2, 3], dtype=np.int8).dtype)
print(np.array([1, 2, 3], dtype="byte").dtype)
print(np.array([1, 2, 3], dtype="int8").dtype)
print(np.array([1, 2, 3], dtype="b").dtype)

int8
int8
int8
int8


## NumPyに用意された符号付き整数の型
<table>
    <thead>
        <tr>
            <th>データ型</th>
            <th>エイリアス</th>
            <th>文字列指定</th>
            <th>説明</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><m-b>numpy.byte</m-b></td>
            <td><m-b>int8</m-b></td>
            <td>
                <ul>
                    <li><m-b>"byte"</m-b></li>
                    <li><m-b>"int8"</m-b></li>
                </ul>
            </td>
            <td>8ビット符号付き整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.short</m-b></td>
            <td><m-b>int16</m-b></td>
            <td>
                <ul>
                    <li><m-b>"short"</m-b></li>
                    <li><m-b>"int16"</m-b></li>
                </ul>
            </td>
            <td>16ビット符号付き整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.intc</m-b></td>
            <td><m-b>int32</m-b></td>
            <td>
                <ul>
                    <li><m-b>"intc"</m-b></li>
                    <li><m-b>"int32"</m-b></li>
                </ul>
            </td>
            <td>32ビット符号付き整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.int_</m-b></td>
            <td>
                <ul>
                    <li><m-b>int64</m-b></li>
                    <li><m-b>intp</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"int_"</m-b></li>
                    <li><m-b>"int64"</m-b></li>
                </ul>
            </td>
            <td>64ビット符号付き整数</td>
        </tr>
    </tbody>
</table>

## NumPyに用意された符号なし整数の型
<table>
    <thead>
        <tr>
            <th>データ型</th>
            <th>エイリアス</th>
            <th>文字列指定</th>
            <th>説明</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><m-b>numpy.ubyte</m-b></td>
            <td><m-b>uint8</m-b></td>
            <td>
                <ul>
                    <li><m-b>"ubyte"</m-b></li>
                    <li><m-b>"uint8"</m-b></li>
                </ul>
            </td>
            <td>8ビット符号なし整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.ushort</m-b></td>
            <td><m-b>uint16</m-b></td>
            <td>
                <ul>
                    <li><m-b>"ushort"</m-b></li>
                    <li><m-b>"uint16"</m-b></li>
                </ul>
            </td>
            <td>16ビット符号なし整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.uintc</m-b></td>
            <td><m-b>uint32</m-b></td>
            <td>
                <ul>
                    <li><m-b>"uintc"</m-b></li>
                    <li><m-b>"uint32"</m-b></li>
                </ul>
            </td>
            <td>32ビット符号なし整数</td>
        </tr>
        <tr>
            <td><m-b>numpy.uint</m-b></td>
            <td>
                <ul>
                    <li><m-b>uint64</m-b></li>
                    <li><m-b>uintp</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"uint_"</m-b></li>
                    <li><m-b>"uint64"</m-b></li>
                    <li><m-b>"uintp"</m-b></li>
                </ul>
            </td>
            <td>64ビット符号なし整数</td>
        </tr>
    </tbody>
</table>

## NumPyに用意された浮動小数型
<table>
    <thead>
        <tr>
            <th>データ型</th>
            <th>エイリアス</th>
            <th>文字列指定</th>
            <th>説明</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><m-b>numpy.half</m-b></td>
            <td><m-b>float16</m-b></td>
            <td>
                <ul>
                    <li><m-b>"half"</m-b></li>
                    <li><m-b>"float16"</m-b></li>
                </ul>
            </td>
            <td>16ビット(半精度)浮動小数点数</td>
        </tr>
        <tr>
            <td><m-b>numpy.single</m-b></td>
            <td><m-b>float32</m-b></td>
            <td>
                <ul>
                    <li><m-b>"single"</m-b></li>
                    <li><m-b>"float32"</m-b></li>
                </ul>
            </td>
            <td>32ビット(単精度)浮動小数点数</td>
        </tr>
        <tr>
            <td><m-b>numpy.double</m-b></td>
            <td>
                <ul>
                    <li><m-b>float64</m-b></li>
                    <li><m-b>float_</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"double"</m-b></li>
                    <li><m-b>"flaot64"</m-b></li>
                </ul>
            </td>
            <td>64ビット(倍精度)浮動小数点数</td>
        </tr>
        <tr>
            <td><m-b>numpy.longdouble</m-b></td>
            <td>
                <ul>
                    <li><m-b>float128</m-b></li>
                    <li><m-b>longfloat</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"longdouble"</m-b></li>
                    <li><m-b>"float128"</m-b></li>
                    <li><m-b>"longfloat"</m-b></li>
                </ul>
            </td>
            <td>128ビット(拡張倍精度)浮動小数点数</td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th>データ型</th>
            <th>エイリアス</th>
            <th>文字列指定</th>
            <th>説明</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><m-b>numpy.csingle</m-b></td>
            <td>
                <ul>
                    <li><m-b>singlecomplex</m-b></li>
                    <li><m-b>complex64</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"csingle"</m-b></li>
                    <li><m-b>"singlecomplex"</m-b></li>
                    <li><m-b>"complex64"</m-b></li>
                </ul>
            </td>
            <td>実部、虚部にそれぞれ32ビット浮動小数点数を使う複素数</td>
        </tr>
        <tr>
            <td><m-b>numpy.cdouble</m-b></td>
            <td>
                <ul>
                    <li><m-b>cfloat</m-b></li>
                    <li><m-b>complex_</m-b></li>
                    <li><m-b>complex128</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"cdouble"</m-b></li>
                    <li><m-b>"cfloat"</m-b></li>
                    <li><m-b>"complex128"</m-b></li>
                </ul>
            </td>
            <td>実部、虚部にそれぞれ64ビット浮動小数点数を使う複素数</td>
        </tr>
        <tr>
            <td><m-b>numpy.clongdouble</m-b></td>
            <td>
                <ul>
                    <li><m-b>clongfloat</m-b></li>
                    <li><m-b>longcomplex</m-b></li>
                    <li><m-b>complex256</m-b></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><m-b>"clongdouble"</m-b></li>
                    <li><m-b>"clongfloat"</m-b></li>
                    <li><m-b>"complex256"</m-b></li>
                </ul>
            </td>
            <td>実部、虚部にそれぞれ128ビット浮動小数点数を使う複素数</td>
        </tr>
    </tbody>
</table>


In [8]:
i = np.uint8(128)
print(i)
print(type(i))
print(i.dtype)

128
<class 'numpy.uint8'>
uint8


In [9]:
f = np.single("0.125")
print(f)
print(type(f))
print(f.dtype)

0.125
<class 'numpy.float32'>
float32


In [14]:
f = np.single(0.001)
print(f)
print(type(f))
print(f.dtype)

0.001
<class 'numpy.float32'>
float32


In [16]:
np.iinfo(np.intc)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [18]:
np.iinfo(1)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [20]:
np.finfo(np.double)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [22]:
np.iinfo(np.complex64)

ValueError: Invalid integer data type 'c'.

In [24]:
np.finfo(np.csingle)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [ ]:
# Pythonの組み込みの数値型に対する暗黙の型変換
np.array([1]).dtype

dtype('int64')

In [27]:
np.array([0.1]).dtype

dtype('float64')

In [29]:
np.array([1 - 2j]).dtype

dtype('complex128')

In [ ]:
# 明示的な型変換
np.array([1]).astype(np.byte)

array([1], dtype=int8)

In [31]:
np.array([0.3, -4.9, 123.456]).astype(np.intc)

array([  0,  -4, 123], dtype=int32)

In [33]:
# オーバーフロー
a = np.uint8(0)
b = np.uint8(1)
a - b

C:\Users\kgrmr\AppData\Local\Temp\ipykernel_28300\3836418833.py:4: RuntimeWarning: overflow encountered in scalar subtract
  a - b


np.uint8(255)

In [34]:
a = np.uint8(255)
b = np.uint8(1)
a + b

C:\Users\kgrmr\AppData\Local\Temp\ipykernel_28300\3252698734.py:3: RuntimeWarning: overflow encountered in scalar add
  a + b


np.uint8(0)

In [36]:
10 ** 20

100000000000000000000

In [39]:
np.power(10, 20, dtype=np.int64)

np.int64(7766279631452241920)

In [48]:
print(np.equal(10**10, np.power(10, 10, dtype=np.int64)))
print(np.equal(10**20, np.power(10, 20, dtype=np.int64)))

True
False


In [38]:
np.power(10, 20, dtype=np.float32)

np.float32(1e+20)

In [40]:
np.power(10, 100, dtype=np.float32)

C:\Users\kgrmr\AppData\Local\Temp\ipykernel_28300\1215880753.py:1: RuntimeWarning: overflow encountered in power
  np.power(10, 100, dtype=np.float32)


np.float32(inf)

In [42]:
np.divide(np.inf, np.inf)

C:\Users\kgrmr\AppData\Local\Temp\ipykernel_28300\3650871706.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(np.inf, np.inf)


np.float64(nan)

In [35]:
# 暗黙の型変換
a = np.array([12, 23, 34], dtype=np.uint8)
b = np.array([-1.23, 4.5, -67.8], dtype=np.double)
a + b

array([ 10.77,  27.5 , -33.8 ])